Feat/create terraform dev
refinancy/refinancy-be pull request #22
Opened 2024-05-06 00:25 UTC by nicolas-limadev

2024-06-01 09:46 UTC, manoelduran approved these changes

2024-09-16 23:28 UTC, raphael-foliveira requested changes
Linhas nos finais de arquivos

2024-09-16 23:28 UTC, raphael-foliveira commented on .dockerignore
> +/ansible
Acrescentar linha no final do arquivo

2024-09-16 23:28 UTC, raphael-foliveira commented on terraform/outputs.tf
> +}
Linha no final do arquivo

2024-09-16 23:28 UTC, raphael-foliveira commented on terraform/terraform-dev/machine.tf
> +}
Linha no final do arquivo

2024-09-16 23:28 UTC, raphael-foliveira commented on terraform/terraform-dev/main.tf
> +}
Linha no final do arquivo

2024-09-16 23:31 UTC, manoelduran requested changes

2024-09-16 23:31 UTC, manoelduran commented on terraform/terraform-dev/public_ip.txt
> +
não entendi este arquivo?

2024-09-16 23:59 UTC, raphael-foliveira commented on terraform/terraform-dev/public_ip.txt
> +
Também não entendi

2024-09-17 00:06 UTC, nicolas-limadev commented on terraform/terraform-dev/public_ip.txt
> +
O terraform gera esse arquivo automaticamente como output para mostrar o ip público da EC2

2024-09-24 20:19 UTC, raphael-foliveira approved these changes

2024-11-29 11:17 UTC, merged